export const LanguageCatalog = {
  en_US: {
    Search: 'Search',
    Cancel: 'Cancel',
    Height: 'Height',
    Weight: 'Weight',
    HP: 'HP',
    Attack: 'Attack',
    Defense: 'Defense',
    Speed: 'Speed',
    Sp_Atk: 'Sp Atk',
    Sp_Def: 'Sp Def',
    Error: 'Error',
    Information: 'Information',
    Not_Found_Pokemon: 'Not Found Pokemon...',
    STATISTICS: 'S T A T I S T I C S',
    Not_Found_Description: 'Not Found Description',
    Not_Found_Details: 'Not Found Details',
    Error_to_get_Pokemons: 'Error to list the pokemons...',
  },
  es_MX: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Información',
    Not_Found_Pokemon: 'No se encontro Pokemon...',
    STATISTICS: 'E S T A D I S T I C A S',
    Not_Found_Description: 'No se encontro Descripción',
    Not_Found_Details: 'No se encontro Detalles',
    Error_to_get_Pokemons: 'Error al listar los pokemones...',
  },

  es_US: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Información',
    Not_Found_Pokemon: 'No se encontro Pokemon...',
    STATISTICS: 'S T A T I S T I C S',
    Not_Found_Description: 'No se encontro Descripción',
    Not_Found_Details: 'No se encontro Detalles',
    Error_to_get_Pokemons: 'Error al listar los pokemones...',
  },

  es_ES: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Información',
    Not_Found_Pokemon: 'No se encontro Pokemon...',
    STATISTICS: 'E S T A D I S T I C A S',
    Not_Found_Description: 'No se encontro Descripción',
    Not_Found_Details: 'No se encontro Detalles',
    Error_to_get_Pokemons: 'Error al listar los pokemones...',
  },
};
