export const LanguageCatalog = {
  en_US: {
    Search: 'Search',
    Cancel: 'Cancel',
    Height: 'Height',
    Weight: 'Weight',
    HP: 'HP',
    Attack: 'Attack',
    Defense: 'Defense',
    Speed: 'Speed',
    Sp_Atk: 'Sp Atk',
    Sp_Def: 'Sp Def',
    Error: 'Error',
    Information: 'Information',
  },
  es_MX: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Información',
  },

  es_US: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Information',
  },

  es_ES: {
    Search: 'Buscar',
    Cancel: 'Cancelar',
    Height: 'Altura',
    Weight: 'Peso',
    HP: 'HP',
    Attack: 'Ataque',
    Defense: 'Defensa',
    Speed: 'Velocidad',
    Sp_Atk: 'Vel Atq',
    Sp_Def: 'Vel Def',
    Error: 'Error',
    Information: 'Información',
  },
};
